### PR TITLE
Raj

### PR DESCRIPTION
**Pull request by rdhaliwal6**
Js validation is added for the parent/ guardian. Also fixed typos and error.

### CODE REVIEW

**Review by rcox18 — CHANGES_REQUESTED** [review]
the if checks need to hide the errors with else statements

**Review by dystopiceyre — APPROVED** [review]

**Review by dystopiceyre — APPROVED** [review]

**Review by dystopiceyre — APPROVED** [review]

**Review by MrPOLO11 — APPROVED** [review]
Cool

**Review by rdhaliwal6 — COMMENTED** [review]
edited and reviewed

**Review by MrPOLO11 — APPROVED** [review]
hello

**Pull request merged**
